language: php

php:
  - 7.1.3

services:
  - mysql

before_script:
 # - mkdir bootstrap/cache
  #- mkdir storage
  #- mkdir storage/app
  #- mkdir storage/framework
  #- mkdir storage/framework/sessions
  #- mkdir storage/framework/cache
  #- mkdir storage/framework/views
  - chmod 777 -R storage
  - chmod 777 -R bootstrap/cache
  #- chown -R www-data:www-data storage
  - cp .env.travis .env
  - mysql -e 'create database homestead_test;'
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate
  - php artisan vendor:publish  --tag=storage
  - php artisan migrate --seed

script:
  - vendor/bin/phpunit
